apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluid-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluid-ai
  template:
    metadata:
      labels:
        app: fluid-ai
    spec:
      containers:
        - name: fluid-ai
          image: fluidAi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20